name: Deploy to Deta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Deta CLI
      run: curl -fsSL https://get.deta.dev/cli.sh | sh

    - name: Deploy to Deta
      env:
        DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
      run: deta deploy
